name: Ainur Bruh Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Ainur-Actions-Test-Job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Unit tests
        run: npm run test:unit

      - name: Build and push image
        run: |
          docker build -t test-vue-build-nginx .
          docker tag test-vue-build-nginx garifullin2000/test-vue-build-nginx
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push garifullin2000/test-vue-build-nginx

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to local machine
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "Hello from GitHub Actions!"'
