name: Ainur Bruh Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Ainur-Actions-Test-Job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Unit tests
        run: npm run test:unit

      - name: Unit tests
        run: npm run test:unit
